=== FaitAccompli/asset-tracker-cloud-docs/docs/firmware/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/bifravst/bifravst/blob/saga/docs/firmware/schema.json",
  "title": "Bifravst Firmware Sensor Data and Configuration",
  "description": "Describes the data published by the device and its configuration options.",
  "type": "object",
  "properties": {
    "cfg": {
      "description": "Configures the device",
      "type": "object",
      "properties": {
        "act": {
          "description": "Whether to enable the active mode",
          "type": "boolean"
        },
        "actwt": {
          "description": "In active mode: wait this amount of seconds until sending the next update. The actual interval will be this time plus the time it takes to get a GPS fix.",
          "type": "integer",
          "minimum": 1
        },
        "mvres": {
          "description": "(movement resolution) In passive mode: Time in seconds to wait after detecting movement before sending the next update",
          "type": "integer",
          "minimum": 1
        },
        "mvt": {
          "description": "(movement timeout) In passive mode: Send update at least this often (in seconds)",
          "type": "integer",
          "minimum": 1
        },
        "gpst": {
          "description": "GPS treshold (in seconds): timeout for GPS fix",
          "type": "integer",
          "minimum": 1
        },
        "acct": {
          "description": "Accelerometer threshold: minimal absolute value for and accelerometer reading to be considered movement. Divide by 10 to get the real threshold. Integers are used because the nRF9160 has issue parsing JSON floats.",
          "type": "integer",
          "minimum": 0
        }
      },
      "required": ["act", "actwt", "mvres", "mvt", "gpst", "acct"]
    },
    "bat": {
      "description": "Battery reading in millivolt",
      "type": "object",
      "properties": {
        "v": {
          "description": "Battery reading read by the modem",
          "type": "integer",
          "minimum": 1
        },
        "ts": {
          "description": "Timestamp with millisecond precision and timezone",
          "type": "string",
          "pattern": "^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$"
        }
      },
      "required": ["v", "ts"]
    },
    "acc": {
      "description": "The accelerometer reading",
      "type": "object",
      "properties": {
        "v": {
          "description": "Accelerometer reading: x,y,z in m/sÂ²",
          "type": "array",
          "items": {
            "type": "number"
          },
          "minItems": 3,
          "maxItems": 3
        },
        "ts": {
          "description": "Timestamp with millisecond precision and timezone",
          "type": "string",
          "pattern": "^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$"
        }
      },
      "required": ["v", "ts"]
    },
    "gps": {
      "description": "The GPS reading",
      "type": "object",
      "properties": {
        "v": {
          "type": "object",
          "properties": {
            "lng": {
              "description": "Longitude",
              "type": "number"
            },
            "lat": {
              "description": "Latitude",
              "type": "number"
            },
            "acc": {
              "description": "Accuracy (2D 1-sigma) in meters",
              "type": "number",
              "minimum": 0
            },
            "alt": {
              "description": "Altitude above WGS-84 ellipsoid in meters",
              "type": "number"
            },
            "spd": {
              "description": "Horizontal speed in meters",
              "type": "number",
              "minimum": 0
            },
            "hdg": {
              "description": "Heading of movement in degrees",
              "type": "number",
              "minimum": 0,
              "maximum": 360
            }
          },
          "required": ["lng", "lat", "acc", "alt", "spd", "hdg"]
        },
        "ts": {
          "description": "Timestamp with millisecond precision and timezone",
          "type": "string",
          "pattern": "^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$"
        }
      },
      "required": ["v", "ts"]
    }
  },
  "required": ["cfg"]
}

=== FaitAccompli/asset-tracker-cloud-docs/docs/firmware/state.json
{
  "bat": {
    "v": 2754,
    "ts": "2019-07-24T11:45:47.123Z"
  },
  "acc": {
    "v": [0.2, 0.777, -4.7],
    "ts": "2019-07-24T11:45:43.666Z"
  },
  "gps": {
    "v": {
      "lng": 10.436642,
      "lat": 63.421133,
      "acc": 24.798573,
      "alt": 170.528305,
      "spd": 0.579327,
      "hdg": 176.12
    },
    "ts": "2019-07-24T11:45:52.991Z"
  },
  "cfg": {
    "gpst": 720,
    "act": false,
    "actwt": 60,
    "mvres": 60,
    "mvt": 3600,
    "acct": 12
  }
}
